baseURL = 'https://understandingconsciousness.github.io/'
languageCode = 'en-us'
title = 'Understanding Consciousness'
theme = 'PaperMod'

[params]
  env = "production"
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowWordCount = false
  hidePoweredBy = true
  
  [params.homeInfoParams]
    Title = "Understanding Consciousness"
    Content = "Here, I share honest reflections on life and the discoveries that emerge from quiet moments of meditation and mindful observation."

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 20